# Generated by Django 5.0.6 on 2026-04-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='ለምሳሌ 2018 ዓ/ም', max_length=16, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('plan_window_open', models.BooleanField(default=False, help_text='የዕቅድ መቀበያ መስኮት ክፍት ነው?')),
            ],
            options={
                'verbose_name': 'የበጀት ዓመት',
                'verbose_name_plural': 'የበጀት ዓመቶች',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_am', models.CharField(help_text='የአገልግሎት ዘርፍ ስም', max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'የአገልግሎት ዘርፍ',
                'verbose_name_plural': 'የአገልግሎት ዘርፎች',
                'ordering': ['name_am'],
            },
        ),
        migrations.CreateModel(
            name='ReportWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'አንደኛ ሩብ ዓመት'), (2, 'ሁለተኛ ሩብ ዓመት'), (3, 'ሦስተኛ ሩብ ዓመት'), (4, 'አራተኛ ሩብ ዓመት')])),
                ('is_open', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_windows', to='ministries.fiscalyear')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_windows', to='ministries.ministry')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fiscal_year', 'ministry', 'quarter'],
                'unique_together': {('fiscal_year', 'ministry', 'quarter')},
            },
        ),
    ]
