# Generated by Django 5.0.6 on 2026-04-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'ረቂቅ'), ('submitted', 'ቀርቧል'), ('approved', 'ጸድቋል'), ('returned', 'ለክለሳ ተመልሷል')], default='draft', max_length=16)),
                ('introduction', models.TextField(blank=True, help_text='መግቢያ')),
                ('general_objective', models.TextField(blank=True, help_text='አጠቃላይ ዓላማ')),
                ('assumptions', models.TextField(blank=True, help_text='የዕቅዱ ታሳቢዎች')),
                ('monitoring_evaluation', models.TextField(blank=True, help_text='የክትትልና ግምገማ ሥራዎች')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, help_text='የሽማግሌ አስተያየት')),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='ministries.fiscalyear')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='ministries.ministry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plans', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ዕቅድ',
                'verbose_name_plural': 'ዕቅዶች',
                'ordering': ['-fiscal_year__starts_on'],
                'unique_together': {('ministry', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='PlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(help_text='ግብ ርዕስ', max_length=512)),
                ('description', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.plan')),
            ],
            options={
                'verbose_name': 'ዋና ግብ',
                'verbose_name_plural': 'ዋና ዋና ግቦች',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(help_text='ተግባራት', max_length=512)),
                ('measure', models.CharField(blank=True, help_text='መለኪያ', max_length=64)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='ብዛት', max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='የነጠላ ዋጋ', max_digits=14, null=True)),
                ('note', models.CharField(blank=True, help_text='መግለጫ', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='plans.plan')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='plans.plangoal')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(help_text='የሚጠበቅ ውጤት', max_length=512)),
                ('measure', models.CharField(blank=True, help_text='መለኪያ', max_length=128)),
                ('quantity', models.CharField(blank=True, help_text='ብዛት', max_length=64)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='plans.plangoal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(help_text='ዝርዝር ተግባር', max_length=1024)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='plans.planoutput')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('risk', models.TextField(help_text='ሊያጋጥሙ የሚችሉ ተግዳሮቶች')),
                ('mitigation', models.TextField(blank=True, help_text='የመፍትሄ እርምጃ')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='plans.plan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.CharField(max_length=1024)),
                ('q1', models.BooleanField(default=False)),
                ('q2', models.BooleanField(default=False)),
                ('q3', models.BooleanField(default=False)),
                ('q4', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plangoal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='plans.plan')),
            ],
            options={
                'ordering': ['goal__order'],
            },
        ),
        migrations.CreateModel(
            name='PlanBudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_total', models.DecimalField(decimal_places=2, default=0, help_text='የተጠየቀ በጀት', max_digits=14)),
                ('q1_budget', models.DecimalField(decimal_places=2, default=0, help_text='አንደኛ ሩብ ዓመት', max_digits=14)),
                ('q2_budget', models.DecimalField(decimal_places=2, default=0, help_text='ሁለተኛ ሩብ ዓመት', max_digits=14)),
                ('q3_budget', models.DecimalField(decimal_places=2, default=0, help_text='ሦስተኛ ሩብ ዓመት', max_digits=14)),
                ('q4_budget', models.DecimalField(decimal_places=2, default=0, help_text='አራተኛ ሩብ ዓመት', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='plans.plan')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='plans.plangoal')),
            ],
            options={
                'unique_together': {('plan', 'goal')},
            },
        ),
    ]
