# Generated by Django 5.0.6 on 2026-04-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('plan_save', 'ዕቅድ ተቀምጧል'), ('plan_submit', 'ዕቅድ ቀርቧል'), ('plan_approve', 'ዕቅድ ጸድቋል'), ('plan_return', 'ዕቅድ ለክለሳ ተመልሷል'), ('report_save', 'ሪፖርት ተቀምጧል'), ('report_submit', 'ሪፖርት ቀርቧል'), ('window_open', 'መስኮት ተከፍቷል'), ('window_close', 'መስኮት ተዘግቷል'), ('user_create', 'ተጠቃሚ ተፈጥሯል'), ('user_disable', 'ተጠቃሚ ታግዷል'), ('ministry_create', 'ዘርፍ ተፈጥሯል'), ('doc_upload', 'ሰነድ ተጭኗል')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ኦዲት ምዝገባ',
                'verbose_name_plural': 'ኦዲት ምዝገቦች',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
