# Generated by Django 5.0.6 on 2026-04-26 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'አንደኛ ሩብ ዓመት'), (2, 'ሁለተኛ ሩብ ዓመት'), (3, 'ሦስተኛ ሩብ ዓመት'), (4, 'አራተኛ ሩብ ዓመት')])),
                ('status', models.CharField(choices=[('locked', 'ተቆልፏል'), ('open', 'ክፍት'), ('draft', 'ረቂቅ'), ('submitted', 'ቀርቧል')], default='locked', max_length=16)),
                ('introduction', models.TextField(blank=True, help_text='መግቢያ')),
                ('quantitative_results', models.TextField(blank=True, help_text='አሃዛዊ ውጤቶች')),
                ('unplanned_activities', models.TextField(blank=True, help_text='በዕቅድ ሳይካተቱ የተከናወኑ ተግባራት')),
                ('challenges', models.TextField(blank=True, help_text='ተግዳሮቶች')),
                ('best_practices', models.TextField(blank=True, help_text='መልካም ልምዶች')),
                ('prayer_topics', models.TextField(blank=True, help_text='የጸሎት/የምስጋና ርዕሶች')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_reports', to='plans.plan')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ሩብ ዓመት ሪፖርት',
                'verbose_name_plural': 'ሩብ ዓመት ሪፖርቶች',
                'ordering': ['quarter'],
                'unique_together': {('plan', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='NextQuarterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(help_text='ለቀጣዩ ሩብ ዓመት የሚከናወን ተግባር')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_quarter_plans', to='reports.quarterlyreport')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarriedOverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='ተግባር')),
                ('note', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_over_tasks', to='reports.quarterlyreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.CharField(help_text='ዝርዝር ተግባር', max_length=1024)),
                ('planned', models.TextField(blank=True, help_text='ለሩብ ዓመቱ የታቀዱ ተግባራት')),
                ('completed_percent', models.PositiveSmallIntegerField(default=0, help_text='የተከናወነ %')),
                ('note', models.TextField(blank=True, help_text='መግለጫ')),
                ('is_carried_over', models.BooleanField(default=False, help_text='ካለፈ ሩብ ዓመት የተሻገረ?')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='plans.plangoal')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='reports.quarterlyreport')),
            ],
            options={
                'ordering': ['goal__order'],
            },
        ),
        migrations.CreateModel(
            name='ReportBudgetUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, help_text='የተፈቀደ በጀት', max_digits=14)),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, help_text='ሥራ ላይ የዋለ', max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_utilization', to='plans.plangoal')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_utilization', to='reports.quarterlyreport')),
            ],
            options={
                'unique_together': {('report', 'goal')},
            },
        ),
    ]
